### ISSUE TITLE
Dokumentation falsch, publikationsliste.php existiert nicht

### ISSUE THREAD

**Issue by arwarw** [RRZE-Webteam/CRIS-Plugin_Webbaukasten#12]
Die Dokumentation enthaelt Beispiele wie "", die aber so nicht funktionieren, da publikationsliste.php nicht existiert.

**Comment by xwolfde** [comment]
Dieses Plugin bezieht sich aber auf den alten Webbaukasten, bei dem alles (sofern es in einer aktuellen Version geflegt ist) da sein sollte.
Und dort ist IMHO die Dokumentation auch vollständig: http://www.webbaukasten.fau.de/anwendungen/cris.shtml 

Aber du hast recht, hier in der Readme sollte ggf. noch ein Hinweis zum Donwload und zur Installation rein.
Obwohl...? macht das Sinn? Wer tatsächlich noch den Webbaukasten nutzt, wird der tatsächlich statt über obige URL hier im GitHub suchen? Und wer im GitHub sucht, statt auf der Webseite, braucht der tatsächlich diese Doku?

Ich würde sagen, in der Readme hier wäre ein Verweis auf die Doku der Webseite nötig.

**Comment by xwolfde** [comment]
Hab entsprechende Hinweise in der Readme ergänzt.

Übrigens wird der Webbaukasten nicht mehr weiter gepflegt. Hintergründe dazu gern via direktmails oder face2face :)
